#define DEBUG 1

#define CONFIG_SOC_IEEE802154_SUPPORTED y

#if HARDWARE_VERSION < 3
#define ENC_A 23
#define ENC_B 2
#else
#define ENC_A 10
#define ENC_B 9
#endif

#define MESSAGE_RECEIVED 7
#define BUTTON_SOS 16

#if HARDWARE_VERSION == 1
#define BUTTON_1_PIN 36
#define BUTTON_2_PIN 26
#define BUTTON_3_PIN 19
#define BUTTON_4_PIN 34
#define BUTTON_SOS_PIN 25
#endif

#if HARDWARE_VERSION == 2
#define BUTTON_1_PIN 5
#define BUTTON_2_PIN 26
#define BUTTON_3_PIN 19
#define BUTTON_4_PIN 34
#define BUTTON_SOS_PIN 25
#endif

#if HARDWARE_VERSION == 3
#define BUTTON_1_PIN 13
#define BUTTON_2_PIN 3
#define BUTTON_3_PIN 12
#define BUTTON_4_PIN 11
#define BUTTON_SOS_PIN 8
#endif

#define COMPASS_DRDY_PIN 35

#if HARDWARE_VERSION == 1
#define OLED_HEIGHT 32
#endif

#if HARDWARE_VERSION == 2
#define OLED_HEIGHT 64
#endif

#if HARDWARE_VERSION == 3
#define OLED_HEIGHT 128
#endif

#define OLED_WIDTH 128

#define OLED_RESET -1

#define DEFAULT_MAX_CALLBACKS 0xF0000000

#define BUTTON_TEXT_MAX 12
#define NODE_TEXT_MAX 32

#define SIZE_SETTINGS_OBJECT 4096
#define SIZE_SAVED_MESSAGES_OBJECT 4096
#define SIZE_COORDS_OBJECT 8192
#define EEPROM_SAVED_MESSAGES_ADDR EEPROM_SETTINGS_ADDR + SIZE_SETTINGS_OBJECT
#define SIZE_STATUSES_OBJECT 4096
#define EEPROM_SETTINGS_ADDR 0
#define EEPROM_STATUSES_ADDR SIZE_SETTINGS_OBJECT
#define EEPROM_SETTINGS_SIZE SIZE_SETTINGS_OBJECT + SIZE_STATUSES_OBJECT
#define ARDUINOJSON_USE_INT64 1
#define ARDUINOJSON_USE_LONG_LONG 1
#define USERID_SIZE_BYTES 8

#if HARDWARE_VERSION == 1

#endif

#if HARDWARE_VERSION == 2
#define NUM_LEDS 31
#define LED_PIN 27
#endif

// TODO: Change this
#if HARDWARE_VERSION == 3
#define NUM_LEDS 60
#define LED_PIN 16
#define AUX_LED_ENABLE_PIN 15
#endif

#define LED_TYPE WS2812B
#define LED_ORDER GRB

// #define UPLOAD_SETTINGS 1
// #define GENERATE_NEW_USERID 1

#define WRITE_STATUSES_TO_EEPROM 1

#ifndef USE_FAKE_GPS_COORDS
#define USE_FAKE_GPS_COORDS 0
#endif

#if USE_FAKE_GPS_COORDS == 1
#define FAKE_GPS_LAT 33.753746
#define FAKE_GPS_LON -84.386330
#elif USE_FAKE_GPS_COORDS == 2
#define FAKE_GPS_LAT 40.730610
#define FAKE_GPS_LON -73.935242
#elif USE_FAKE_GPS_COORDS == 3
#define FAKE_GPS_LAT 37.773972
#define FAKE_GPS_LON -122.431297
#elif USE_FAKE_GPS_COORDS != 0
#define FAKE_GPS_LAT 51.509865
#define FAKE_GPS_LON -0.118092
#endif

// test comment